spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/codelab_db?serverTimezone=Asia/Seoul&useSSL=false&characterEncoding=utf-8
    username: codelab
    password: codelab
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update # 없으면 만들고 있으면 그대로 사용
    show-sql: true # mysql debug mode, 실제 쿼리가 로그로 보임
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate: # custom options
        format_sql: true # sql 로그를 포매팅해서 보여줌
logging:
  level:
    org.hibernate.type: trace # bind 쿼리의 내용까지 출력. ? 부분이 실제 값으로 표현됨
server:
  port: 8080
security:
  oauth2:
    client:
      client-id: client
      client-secret: password
    resource:
      token-info-uri: http://localhost:8081/oauth/check_token # 인증서버 URL
management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
info:
  app:
    name: Hello
    java:
      source: 1.8